### ISSUE TITLE
move to JuliaIO?

### ISSUE THREAD

**Issue by stevengj** [JuliaIO/Blosc.jl#27]
Since HDF5 and JLD depend on this, although Blosc is not really "IO" specifically.  @tkelman, @timholy?

**Comment by tkelman** [comment]
Makes sense to me to have them the same place. Maybe we make a JuliaCompression org eventually (or one of the reasons I had a different preference for the name of what the JuliaArchive org currently is...)

**Comment by laborg** [comment]
@stevengj @ararslan Could this be done? Especially the dependency of HDF5 would be a good reason to do this. (My motivation: Packagecompiler would work better if HDF5 would rely on blosc_jll for which a new release of Blosc.jl is needed).

**Comment by stevengj** [comment]
I'm fine with this, but I'm not currently a member of the JuliaIO org, so I don't think I have permission to move it?

**Comment by ararslan** [comment]
You have a pending invitation to join JuliaIO 😄

**Comment by stevengj** [comment]
Done.
