### ISSUE TITLE
Blosc2 support?

### ISSUE THREAD

**Issue by rana** [JuliaIO/Blosc.jl#78]
Hi,

What are your thoughts on supporting Blosc2?

Thank you,

Rana

* https://www.blosc.org/posts/mid-2020-progress-report/
* https://blosc-doc.readthedocs.io/en/latest/#c-blosc2-a-simple-compressed-fast-and-persistent-data-store-library-for-c
* https://github.com/Blosc/c-blosc2

**Comment by mkitti** [comment]
Note there is Blosc2 support in development at https://github.com/waralex/Blosc2.jl

The binaries are available at
https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl
