### ISSUE TITLE
GC.@preserve the results of cbuffer_sizes

### ISSUE THREAD

**Issue by mkitti** [JuliaIO/Blosc.jl#86]
For reasons unclear to me, it may be necessary to `GC.@preserve` the results of `Blosc.cbuffer_sizes`, otherwise the original buffer may become corrupted. This occurs starting with Julia 1.8 in development.

https://github.com/JuliaIO/HDF5.jl/pull/880#discussion_r767195931

**Comment by musm** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/43408  ?
